class_name State
enum {
    SPRITES_ENTERING,
    SUMMON_FAMILIARS,
    CHOOSE_ACTION,
    PARTY_MENU,
    ITEM_MENU,
    CHOOSE_MOVE,
    CHOOSE_TARGET,
    BEGIN_TURN,
    ANIMATE_MOVE,
    EXECUTE_MOVE,
    EVALUATE_MOVE,
    ANNOUNCE_WINNER,
    NAME_FAMILIAR,
    LEARN_MOVE,
}